<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitdf1d43eceb8024d63ac204e17657d2f7
{
    public static $prefixLengthsPsr4 = array (
        'W' => 
        array (
            'Webinv\\Datatables\\' => 18,
        ),
        'P' => 
        array (
            'Psr\\Http\\Message\\' => 17,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Webinv\\Datatables\\' => 
        array (
            0 => __DIR__ . '/..' . '/webinv/datatables/src/Datatables',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitdf1d43eceb8024d63ac204e17657d2f7::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitdf1d43eceb8024d63ac204e17657d2f7::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
